//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_holdingGunLeft : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Swim
        {
            get
            {
                return SteamVR_Actions.holdingGunLeft_Swim;
            }
        }
        
        public virtual SteamVR_Action_Boolean SpawnReload
        {
            get
            {
                return SteamVR_Actions.holdingGunLeft_SpawnReload;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.holdingGunLeft_Fire;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapWeapon
        {
            get
            {
                return SteamVR_Actions.holdingGunLeft_SwapWeapon;
            }
        }
    }
}
